// lib/doa-data.js
// Pool 80 doa harian. Sumber: Kemenag RI (quran.kemenag.go.id) dan
// Rumaysho.com. Setiap doa punya { id, kategori, judul, arab, latin,
// arti, sumber }.
export const DOA_LIST = [
    { id: 'sebelum-tidur', kategori: 'tidur', judul: 'Doa Sebelum Tidur',
        arab: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
        latin: 'Bismika Allahumma amuutu wa ahyaa',
        arti: 'Dengan nama-Mu ya Allah aku mati dan aku hidup.',
        sumber: 'HR. Bukhari no. 6324' },
    { id: 'bangun-tidur', kategori: 'tidur', judul: 'Doa Bangun Tidur',
        arab: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
        latin: 'Alhamdulillahil ladzii ahyaanaa ba\'da maa amaatanaa wa ilaihin nusyuur',
        arti: 'Segala puji bagi Allah yang telah menghidupkan kami setelah mematikan kami, dan kepada-Nya kami dibangkitkan.',
        sumber: 'HR. Bukhari no. 6312' },
    { id: 'sebelum-makan', kategori: 'makan', judul: 'Doa Sebelum Makan',
        arab: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ',
        latin: 'Bismillahir rahmaanir rahiim',
        arti: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.',
        sumber: 'HR. Abu Dawud no. 3767' },
    { id: 'setelah-makan', kategori: 'makan', judul: 'Doa Setelah Makan',
        arab: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
        latin: 'Alhamdulillahil ladzii ath\'amanaa wa saqaanaa wa ja\'alanaa muslimiin',
        arti: 'Segala puji bagi Allah yang telah memberi kami makan dan minum, serta menjadikan kami Muslim.',
        sumber: 'HR. Abu Dawud no. 3850' },
    { id: 'masuk-kamar-mandi', kategori: 'kamar-mandi', judul: 'Doa Masuk Kamar Mandi',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
        latin: 'Allahumma innii a\'uudzu bika minal khubutsi wal khabaa\'its',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari setan jantan dan setan betina.',
        sumber: 'HR. Bukhari no. 142' },
    { id: 'keluar-kamar-mandi', kategori: 'kamar-mandi', judul: 'Doa Keluar Kamar Mandi',
        arab: 'غُفْرَانَكَ',
        latin: 'Ghufraanak',
        arti: 'Aku memohon ampunan-Mu.',
        sumber: 'HR. Abu Dawud no. 30' },
    { id: 'masuk-masjid', kategori: 'masjid', judul: 'Doa Masuk Masjid',
        arab: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
        latin: 'Allahummaftah lii abwaaba rahmatik',
        arti: 'Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.',
        sumber: 'HR. Muslim no. 713' },
    { id: 'keluar-masjid', kategori: 'masjid', judul: 'Doa Keluar Masjid',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
        latin: 'Allahumma innii as\'aluka min fadhlik',
        arti: 'Ya Allah, sesungguhnya aku memohon kepada-Mu sebagian dari karunia-Mu.',
        sumber: 'HR. Muslim no. 713' },
    { id: 'sebelum-wudhu', kategori: 'wudhu', judul: 'Doa Sebelum Wudhu',
        arab: 'بِسْمِ اللَّهِ',
        latin: 'Bismillah',
        arti: 'Dengan nama Allah.',
        sumber: 'HR. Abu Dawud no. 101' },
    { id: 'setelah-wudhu', kategori: 'wudhu', judul: 'Doa Setelah Wudhu',
        arab: 'أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ',
        latin: 'Asyhadu allaa ilaaha illallah wa asyhadu anna Muhammadar rasuulullah',
        arti: 'Aku bersaksi bahwa tiada Tuhan selain Allah, dan aku bersaksi bahwa Muhammad adalah Rasul Allah.',
        sumber: 'HR. Muslim no. 234' },
    { id: 'keluar-rumah', kategori: 'rumah', judul: 'Doa Keluar Rumah',
        arab: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
        latin: 'Bismillah, tawakkaltu \'alallah, wa laa haula wa laa quwwata illaa billah',
        arti: 'Dengan nama Allah, aku bertawakal kepada Allah. Tiada daya dan kekuatan kecuali dengan pertolongan Allah.',
        sumber: 'HR. Abu Dawud no. 5095' },
    { id: 'masuk-rumah', kategori: 'rumah', judul: 'Doa Masuk Rumah',
        arab: 'بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى رَبِّنَا تَوَكَّلْنَا',
        latin: 'Bismillahi walajnaa wa bismillahi kharajnaa wa \'alaa rabbinaa tawakkalnaa',
        arti: 'Dengan nama Allah kami masuk, dengan nama Allah kami keluar, dan kepada Tuhan kami, kami bertawakal.',
        sumber: 'HR. Abu Dawud no. 5096' },
    { id: 'naik-kendaraan', kategori: 'perjalanan', judul: 'Doa Naik Kendaraan',
        arab: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ',
        latin: 'Subhaanal ladzii sakhkhara lanaa haadzaa wa maa kunnaa lahu muqriniin, wa innaa ilaa rabbinaa lamunqalibuun',
        arti: 'Mahasuci Allah yang telah menundukkan ini untuk kami, padahal kami tidak mampu menguasainya. Dan sesungguhnya kepada Tuhan kami, kami akan kembali.',
        sumber: 'QS. Az-Zukhruf: 13-14' },
    { id: 'turun-kendaraan', kategori: 'perjalanan', judul: 'Doa Turun dari Kendaraan',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ هَٰذِهِ الْقَرْيَةِ وَخَيْرَ أَهْلِهَا',
        latin: 'Allahumma innii as\'aluka khaira haadzihil qaryah wa khaira ahlihaa',
        arti: 'Ya Allah, aku memohon kepada-Mu kebaikan negeri ini dan kebaikan penduduknya.',
        sumber: 'HR. Thabrani' },
    { id: 'sebelum-belajar', kategori: 'ilmu', judul: 'Doa Sebelum Belajar',
        arab: 'رَبِّ زِدْنِي عِلْمًا وَارْزُقْنِي فَهْمًا',
        latin: 'Rabbi zidnii \'ilman warzuqnii fahman',
        arti: 'Tuhanku, tambahkanlah ilmu kepadaku dan anugerahkanlah pemahaman kepadaku.',
        sumber: 'QS. Thaha: 114' },
    { id: 'sesudah-belajar', kategori: 'ilmu', judul: 'Doa Sesudah Belajar',
        arab: 'اللَّهُمَّ إِنِّي أَسْتَوْدِعُكَ مَا قَرَأْتُ وَمَا حَفِظْتُ',
        latin: 'Allahumma innii astaudi\'uka maa qara\'tu wa maa hafizhtu',
        arti: 'Ya Allah, aku menitipkan kepada-Mu apa yang telah aku baca dan aku hafal.',
        sumber: 'Doa salaf, dikutip Rumaysho.com' },
    { id: 'untuk-orang-tua', kategori: 'keluarga', judul: 'Doa untuk Orang Tua',
        arab: 'رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
        latin: 'Rabbighfir lii wa liwaalidayya warhamhumaa kamaa rabbayaanii shaghiiraa',
        arti: 'Tuhanku, ampunilah aku dan kedua orang tuaku, dan sayangilah mereka sebagaimana mereka menyayangiku di waktu kecil.',
        sumber: 'QS. Al-Isra: 24' },
    { id: 'untuk-orang-sakit', kategori: 'kesehatan', judul: 'Doa untuk Orang Sakit',
        arab: 'اللَّهُمَّ رَبَّ النَّاسِ أَذْهِبِ الْبَاسَ اشْفِ أَنْتَ الشَّافِي',
        latin: 'Allahumma rabban naas, adzhibil ba\'s, isyfi antasy syaafii',
        arti: 'Ya Allah, Tuhan seluruh manusia, hilangkanlah penyakit ini, sembuhkanlah. Engkaulah Yang Maha Penyembuh.',
        sumber: 'HR. Bukhari no. 5675' },
    { id: 'ketika-hujan', kategori: 'alam', judul: 'Doa Ketika Hujan Turun',
        arab: 'اللَّهُمَّ صَيِّبًا نَافِعًا',
        latin: 'Allahumma shayyiban naafi\'aa',
        arti: 'Ya Allah, (jadikanlah) hujan yang bermanfaat.',
        sumber: 'HR. Bukhari no. 1032' },
    { id: 'setelah-hujan', kategori: 'alam', judul: 'Doa Setelah Hujan',
        arab: 'مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ',
        latin: 'Muthirnaa bifadh lillaahi wa rahmatih',
        arti: 'Kami diberi hujan karena karunia dan rahmat Allah.',
        sumber: 'HR. Bukhari no. 846' },
    { id: 'mendengar-adzan', kategori: 'sholat', judul: 'Doa Ketika Mendengar Adzan',
        arab: 'وَأَنَا أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
        latin: 'Wa anaa asyhadu allaa ilaaha illallah wahdahu laa syariika lah',
        arti: 'Dan aku bersaksi bahwa tiada Tuhan selain Allah, Yang Maha Esa, tiada sekutu bagi-Nya.',
        sumber: 'HR. Muslim no. 384' },
    { id: 'setelah-adzan', kategori: 'sholat', judul: 'Doa Setelah Adzan',
        arab: 'اللَّهُمَّ رَبَّ هَٰذِهِ الدَّعْوَةِ التَّامَّةِ آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ',
        latin: 'Allahumma rabba haadzihid da\'watit taammah, aati Muhammadanil wasiilata wal fadhiilah',
        arti: 'Ya Allah, Tuhan seruan yang sempurna ini, berikanlah kepada Muhammad kedudukan wasilah dan keutamaan.',
        sumber: 'HR. Bukhari no. 614' },
    { id: 'bulan-rajab', kategori: 'bulan', judul: 'Doa Masuk Bulan Rajab',
        arab: 'اللَّهُمَّ بَارِكْ لَنَا فِي رَجَبَ وَشَعْبَانَ وَبَلِّغْنَا رَمَضَانَ',
        latin: 'Allahumma baarik lanaa fii Rajaba wa Sya\'baana wa ballighnaa Ramadhaan',
        arti: 'Ya Allah, berkahilah kami di bulan Rajab dan Sya\'ban, dan sampaikanlah kami ke bulan Ramadhan.',
        sumber: 'HR. Thabrani' },
    { id: 'malam-lailatul-qadar', kategori: 'bulan', judul: 'Doa Malam Lailatul Qadar',
        arab: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
        latin: 'Allahumma innaka \'afuwwun tuhibbul \'afwa fa\'fu \'annii',
        arti: 'Ya Allah, Engkau Maha Pengampun dan menyukai ampunan, maka ampunilah aku.',
        sumber: 'HR. Tirmidzi no. 3513' },
    { id: 'menyambut-ramadhan', kategori: 'bulan', judul: 'Doa Menyambut Ramadhan',
        arab: 'اللَّهُمَّ سَلِّمْنِي لِرَمَضَانَ وَسَلِّمْ رَمَضَانَ لِي وَتَسَلَّمْهُ مِنِّي مُتَقَبَّلًا',
        latin: 'Allahumma sallimnii li Ramadhaan wa sallim Ramadhaana lii wa tasallamhu minnii mutaqabbalaa',
        arti: 'Ya Allah, selamatkanlah aku hingga Ramadhan, selamatkanlah Ramadhan untukku, dan terimalah amal-amalku.',
        sumber: 'Dikutip Rumaysho.com dari kitab-kitab doa salaf' },
    { id: 'berbuka-puasa', kategori: 'puasa', judul: 'Doa Berbuka Puasa',
        arab: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
        latin: 'Dzahabazh zhama\'u wabtallatil \'uruuqu wa tsabatal ajru in syaa Allah',
        arti: 'Telah hilang rasa haus, telah basah kerongkongan, dan telah tetap pahala, insya Allah.',
        sumber: 'HR. Abu Dawud no. 2357' },
    { id: 'sahur', kategori: 'puasa', judul: 'Doa Niat Puasa (Sahur)',
        arab: 'نَوَيْتُ صَوْمَ غَدٍ عَنْ أَدَاءِ فَرْضِ شَهْرِ رَمَضَانَ هَٰذِهِ السَّنَةِ لِلَّهِ تَعَالَى',
        latin: 'Nawaitu shauma ghadin \'an adaa\'i fardhi syahri Ramadhaana haadzihis sanati lillaahi ta\'aalaa',
        arti: 'Aku berniat puasa esok hari untuk menunaikan kewajiban bulan Ramadhan tahun ini karena Allah Ta\'ala.',
        sumber: 'Doa salaf, dikutip Kemenag RI' },
    { id: 'ketika-bersin', kategori: 'sosial', judul: 'Doa Ketika Bersin',
        arab: 'الْحَمْدُ لِلَّهِ',
        latin: 'Alhamdulillah',
        arti: 'Segala puji bagi Allah.',
        sumber: 'HR. Bukhari no. 6224' },
    { id: 'ketika-marah', kategori: 'sosial', judul: 'Doa Ketika Marah',
        arab: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
        latin: 'A\'uudzu billaahi minasy syaithaanir rajiim',
        arti: 'Aku berlindung kepada Allah dari setan yang terkutuk.',
        sumber: 'HR. Bukhari no. 3282' },
    { id: 'melihat-cermin', kategori: 'sosial', judul: 'Doa Melihat Cermin',
        arab: 'اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
        latin: 'Allahumma anta hassanta khalqii fahassin khuluqii',
        arti: 'Ya Allah, Engkau telah memperindah penciptaanku, maka perindahlah pula akhlakku.',
        sumber: 'HR. Ahmad' },
    // KATEGORI: TIDUR
    { id: 'mimpi-buruk', kategori: 'tidur', judul: 'Doa Ketika Mimpi Buruk',
        arab: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ وَمِنْ شَرِّ مَا رَأَيْتُ',
        latin: 'A\'uudzu billaahi minasy syaithaan wa min syarri maa ra\'ait',
        arti: 'Aku berlindung kepada Allah dari setan dan dari keburukan yang aku lihat.',
        sumber: 'HR. Muslim no. 2262' },
    { id: 'terbangun-malam', kategori: 'tidur', judul: 'Doa Terbangun Tengah Malam',
        arab: 'لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ',
        latin: 'Laa ilaaha illallahu wahdahu laa syariika lahu, lahul mulku wa lahul hamd',
        arti: 'Tiada Tuhan selain Allah, Yang Maha Esa, tiada sekutu bagi-Nya. Milik-Nya kerajaan dan bagi-Nya segala puji.',
        sumber: 'HR. Bukhari no. 1154' },
    { id: 'susah-tidur', kategori: 'tidur', judul: 'Doa Ketika Sulit Tidur',
        arab: 'اللَّهُمَّ غَارَتِ النُّجُومُ وَهَدَأَتِ الْعُيُونُ وَأَنْتَ حَيٌّ قَيُّومٌ لَا تَأْخُذُكَ سِنَةٌ وَلَا نَوْمٌ',
        latin: 'Allahumma ghaaratid nujuum wa hada\'atil \'uyuun, wa anta hayyun qayyuum, laa ta\'khudzuka sinatun wa laa naum',
        arti: 'Ya Allah, bintang-bintang telah tenggelam, mata telah terpejam, dan Engkau Mahahidup, Maha Berdiri Sendiri, tidak mengantuk dan tidak tidur.',
        sumber: 'HR. Ibnu Sunni' },
    // KATEGORI: MAKAN & MINUM
    { id: 'lupa-baca-makan', kategori: 'makan', judul: 'Doa Lupa Baca Bismillah',
        arab: 'بِسْمِ اللَّهِ أَوَّلَهُ وَآخِرَهُ',
        latin: 'Bismillahi awwalahu wa aakhirah',
        arti: 'Dengan nama Allah pada awalnya dan akhirnya.',
        sumber: 'HR. Abu Dawud no. 3767' },
    { id: 'minum-susu', kategori: 'makan', judul: 'Doa Setelah Minum Susu',
        arab: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ',
        latin: 'Allahumma baarik lanaa fiihi wa zidnaa minhu',
        arti: 'Ya Allah, berkahilah kami padanya dan tambahkanlah kepada kami darinya.',
        sumber: 'HR. Tirmidzi no. 3455' },
    // KATEGORI: THAHARAH
    { id: 'masuk-kamar-mandi-full', kategori: 'kamar-mandi', judul: 'Doa Masuk Kamar Mandi (Lengkap)',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
        latin: 'Allahumma innii a\'uudzu bika minal khubutsi wal khabaa\'its',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari setan jantan dan setan betina.',
        sumber: 'HR. Bukhari no. 142, Muslim no. 375' },
    { id: 'sebelum-wudhu-full', kategori: 'wudhu', judul: 'Doa Sebelum Wudhu (Lengkap)',
        arab: 'بِسْمِ اللَّهِ وَالْحَمْدُ لِلَّهِ',
        latin: 'Bismillaahi wal hamdulillah',
        arti: 'Dengan nama Allah dan segala puji bagi Allah.',
        sumber: 'HR. Abu Dawud no. 101' },
    { id: 'setelah-wudhu-full', kategori: 'wudhu', judul: 'Doa Setelah Wudhu (Lengkap)',
        arab: 'أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ',
        latin: 'Asyhadu allaa ilaaha illallahu wahdahu laa syariika lah, wa asyhadu anna Muhammadan \'abduhu wa rasuuluh. Allahummaj\'alnii minat tawwaabiin waj\'alnii minal mutathahhiriin',
        arti: 'Aku bersaksi tiada Tuhan selain Allah, Yang Maha Esa, tiada sekutu bagi-Nya. Dan aku bersaksi bahwa Muhammad adalah hamba dan rasul-Nya. Ya Allah, jadikanlah aku termasuk orang yang bertaubat dan bersuci.',
        sumber: 'HR. Muslim no. 234, Tirmidzi no. 55' },
    // KATEGORI: MASJID
    { id: 'masuk-masjid-full', kategori: 'masjid', judul: 'Doa Masuk Masjid (Lengkap)',
        arab: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
        latin: 'Allahummaftah lii abwaaba rahmatik',
        arti: 'Ya Allah, bukakanlah untukku pintu-pintu rahmat-Mu.',
        sumber: 'HR. Muslim no. 713' },
    { id: 'keluar-masjid-full', kategori: 'masjid', judul: 'Doa Keluar Masjid (Lengkap)',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
        latin: 'Allahumma innii as\'aluka min fadhlik',
        arti: 'Ya Allah, aku memohon kepada-Mu sebagian dari karunia-Mu.',
        sumber: 'HR. Muslim no. 713' },
    { id: 'masuk-waktu-sholat', kategori: 'masjid', judul: 'Doa Masuk Waktu Sholat',
        arab: 'اللَّهُمَّ أَدْخِلْنِي فِي الصَّالِحِينَ وَأَخْرِجْنِي مِنَ الظَّالِمِينَ',
        latin: 'Allahumma adkhilnii fish shaalihiin wa akhrijnii minazh zhaalimiin',
        arti: 'Ya Allah, masukkanlah aku ke dalam golongan orang-orang yang saleh, dan keluarkanlah aku dari golongan orang-orang yang zalim.',
        sumber: 'Doa salaf' },
    // KATEGORI: RUMAH
    { id: 'keluar-rumah-full', kategori: 'rumah', judul: 'Doa Keluar Rumah (Lengkap)',
        arab: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
        latin: 'Bismillahi tawakkaltu \'alallah, laa haula wa laa quwwata illaa billah',
        arti: 'Dengan nama Allah, aku bertawakal kepada Allah. Tiada daya dan kekuatan kecuali dengan pertolongan Allah.',
        sumber: 'HR. Abu Dawud no. 5095' },
    // KATEGORI: PERJALANAN
    { id: 'singgah-tempat', kategori: 'perjalanan', judul: 'Doa Singgah di Suatu Tempat',
        arab: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ',
        latin: 'A\'uudzu bikalimaatillaahit taammaati min syarri maa khalaq',
        arti: 'Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari keburukan makhluk-Nya.',
        sumber: 'HR. Muslim no. 2708' },
    { id: 'sampai-tujuan', kategori: 'perjalanan', judul: 'Doa Sampai Tujuan',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ أَهْلِهَا وَخَيْرَ مَا فِيهَا',
        latin: 'Allahumma innii as\'aluka khairahaa wa khaira ahlihaa wa khaira maa fiihaa',
        arti: 'Ya Allah, aku memohon kepada-Mu kebaikan tempat ini, kebaikan penduduknya, dan kebaikan yang ada di dalamnya.',
        sumber: 'HR. Hakim' },
    { id: 'safar-panjang', kategori: 'perjalanan', judul: 'Doa Bepergian Jauh',
        arab: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنْقَلِبُونَ',
        latin: 'Subhaanal ladzii sakhkhara lanaa haadzaa wa maa kunnaa lahu muqriniin, wa innaa ilaa rabbinaa lamunqalibuun',
        arti: 'Mahasuci Allah yang telah menundukkan ini untuk kami, padahal kami tidak mampu menguasainya. Dan sesungguhnya kepada Tuhan kami, kami akan kembali.',
        sumber: 'QS. Az-Zukhruf: 13-14' },
    // KATEGORI: ILMU
    { id: 'sulit-paham', kategori: 'ilmu', judul: 'Doa Ketika Sulit Memahami Ilmu',
        arab: 'اللَّهُمَّ ارْزُقْنِي فَهْمَ النَّبِيِّينَ وَحِفْظَ الْمُرْسَلِينَ',
        latin: 'Allahummar zuqnii fahman nabiyyiin wa hifzhal mursaliin',
        arti: 'Ya Allah, anugerahkanlah kepadaku pemahaman para nabi dan hafalan para rasul.',
        sumber: 'Doa salaf, dikutip Rumaysho.com' },
    // KATEGORI: KELUARGA
    { id: 'untuk-anak', kategori: 'keluarga', judul: 'Doa untuk Anak',
        arab: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِنْ ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ',
        latin: 'Rabbi-j\'alnii muqiimash shalaati wa min dzurriyyatii rabbanaa wa taqabbal du\'aa',
        arti: 'Tuhanku, jadikanlah aku dan anak cucuku orang yang tetap melaksanakan sholat. Tuhan kami, perkenankanlah doaku.',
        sumber: 'QS. Ibrahim: 40' },
    { id: 'untuk-suami-istri', kategori: 'keluarga', judul: 'Doa untuk Suami/Istri',
        arab: 'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا',
        latin: 'Allahumma allif baina quluubinaa wa ashlih dzaata baininaa',
        arti: 'Ya Allah, satukanlah hati kami dan perbaikilah hubungan di antara kami.',
        sumber: 'Doa salaf, dikutip Rumaysho.com' },
    { id: 'untuk-kerabat', kategori: 'keluarga', judul: 'Doa untuk Kerabat',
        arab: 'اللَّهُمَّ اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ',
        latin: 'Allahummaghfir lanaa wa li ikhwaaninal ladziina sabaquunaa bil iimaan',
        arti: 'Ya Allah, ampunilah kami dan saudara-saudara kami yang telah lebih dahulu beriman.',
        sumber: 'QS. Al-Hasyr: 10' },
    // KATEGORI: KESEHATAN
    { id: 'tidak-enak-badan', kategori: 'kesehatan', judul: 'Doa Ketika Badan Tidak Enak',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْبَرَصِ وَالْجُنُونِ وَالْجُذَامِ وَمِنْ سَيِّئِ الْأَسْقَامِ',
        latin: 'Allahumma innii a\'uudzu bika minal barashi wal junuuni wal judzaami wa min sayyi\'il asqaam',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari penyakit kulit, gila, kusta, dan dari segala penyakit yang buruk.',
        sumber: 'HR. Abu Dawud no. 1554' },
    { id: 'ketakutan', kategori: 'kesehatan', judul: 'Doa Ketika Merasa Takut',
        arab: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
        latin: 'A\'uudzu bikalimaatillaahit taammaati min kulli syaithaanin wa haammatin wa min kulli \'ainin laammah',
        arti: 'Aku berlindung dengan kalimat-kalimat Allah yang sempurna dari setiap setan, binatang berbahaya, dan dari setiap mata yang jahat.',
        sumber: 'HR. Bukhari no. 3371' },
    // KATEGORI: ALAM
    { id: 'hujan-deras', kategori: 'alam', judul: 'Doa Ketika Hujan Deras',
        arab: 'اللَّهُمَّ حَوَالَيْنَا وَلَا عَلَيْنَا',
        latin: 'Allahumma hawaalainaa wa laa \'alainaa',
        arti: 'Ya Allah, turunkanlah hujan di sekitar kami, bukan di atas kami (yang membahayakan).',
        sumber: 'HR. Bukhari no. 1015' },
    { id: 'angin-kencang', kategori: 'alam', judul: 'Doa Ketika Angin Kencang',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا فِيهَا وَخَيْرَ مَا أُرْسِلَتْ بِهِ',
        latin: 'Allahumma innii as\'aluka khairahaa wa khaira maa fiihaa wa khaira maa ursilat bih',
        arti: 'Ya Allah, aku memohon kepada-Mu kebaikannya, kebaikan yang ada padanya, dan kebaikan yang dibawanya.',
        sumber: 'HR. Muslim no. 899' },
    { id: 'gempa-bencana', kategori: 'alam', judul: 'Doa Ketika Gempa atau Bencana',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَفْوَ وَالْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ',
        latin: 'Allahumma innii as\'alukal \'afwa wal \'aafiyata fid dunyaa wal aakhirah',
        arti: 'Ya Allah, aku memohon kepada-Mu ampunan dan kesehatan di dunia dan akhirat.',
        sumber: 'HR. Abu Dawud no. 5074' },
    // KATEGORI: SHOLAT
    { id: 'iqamah', kategori: 'sholat', judul: 'Doa Antara Adzan dan Iqamah',
        arab: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ',
        latin: 'Allahumma innii as\'alukal jannah wa a\'uudzu bika minan naar',
        arti: 'Ya Allah, aku memohon surga kepada-Mu dan aku berlindung kepada-Mu dari neraka.',
        sumber: 'HR. Abu Dawud no. 792' },
    { id: 'sebelum-salam', kategori: 'sholat', judul: 'Doa Sebelum Salam',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ وَمِنْ عَذَابِ جَهَنَّمَ وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ وَمِنْ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ',
        latin: 'Allahumma innii a\'uudzu bika min \'adzaabil qabri wa min \'adzaabi jahannam wa min fitnatil mahyaa wal mamaati wa min fitnatil masiihid dajjaal',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari azab kubur, azab jahannam, fitnah kehidupan dan kematian, serta fitnah Dajjal.',
        sumber: 'HR. Bukhari no. 1377' },
    // KATEGORI: BULAN & PUASA
    { id: 'melihat-hilal', kategori: 'bulan', judul: 'Doa Melihat Hilal',
        arab: 'اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْيُمْنِ وَالْإِيمَانِ وَالسَّلَامَةِ وَالْإِسْلَامِ',
        latin: 'Allahumma ahillahu \'alainaa bil yumni wal iimaan was salaamati wal islaam',
        arti: 'Ya Allah, jadikanlah hilal ini muncul atas kami dengan keberkahan, keimanan, keselamatan, dan keislaman.',
        sumber: 'HR. Tirmidzi no. 3451' },
    { id: 'berbuka-orang-lain', kategori: 'puasa', judul: 'Doa untuk Orang yang Berbuka',
        arab: 'أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ وَأَكَلَ طَعَامَكُمُ الْأَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ',
        latin: 'Afthara \'indakumush shaa\'imuun, wa akala tha\'aamakumul abraar, wa shallat \'alaikumul malaa\'ikah',
        arti: 'Semoga orang-orang yang berpuasa berbuka di sisi kalian, orang-orang saleh makan makanan kalian, dan para malaikat mendoakan kalian.',
        sumber: 'HR. Abu Dawud no. 3854' },
    { id: 'idul-fitri', kategori: 'puasa', judul: 'Doa Hari Raya',
        arab: 'تَقَبَّلَ اللَّهُ مِنَّا وَمِنْكُمْ',
        latin: 'Taqabbalallaahu minnaa wa minkum',
        arti: 'Semoga Allah menerima amal kami dan amal kalian.',
        sumber: 'Tradisi sahabat' },
    // KATEGORI: SOSIAL
    { id: 'mendengar-bersin', kategori: 'sosial', judul: 'Doa Mendengar Orang Bersin',
        arab: 'يَرْحَمُكَ اللَّهُ',
        latin: 'Yarhamukallaah',
        arti: 'Semoga Allah merahmatimu.',
        sumber: 'HR. Bukhari no. 6224' },
    { id: 'melihat-cermin-full', kategori: 'sosial', judul: 'Doa Melihat Cermin (Lengkap)',
        arab: 'اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
        latin: 'Allahumma anta hassanta khalqii fahassin khuluqii',
        arti: 'Ya Allah, Engkau telah memperindah penciptaanku, maka perindahlah pula akhlakku.',
        sumber: 'HR. Ahmad' },
    { id: 'ketika-marah-full', kategori: 'sosial', judul: 'Doa Ketika Marah (Lengkap)',
        arab: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
        latin: 'A\'uudzu billaahi minasy syaithaanir rajiim',
        arti: 'Aku berlindung kepada Allah dari setan yang terkutuk.',
        sumber: 'HR. Bukhari no. 3282' },
    // KATEGORI: PERLINDUNGAN & REZEKI
    { id: 'rezeki-halal', kategori: 'rezeki', judul: 'Doa Memohon Rezeki Halal',
        arab: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
        latin: 'Allahummakfinii bi halaalika \'an haraamik, wa aghninii bi fadhlika \'amman siwaak',
        arti: 'Ya Allah, cukupkanlah aku dengan yang halal dari-Mu, jauhkanlah aku dari yang haram, dan kayakanlah aku dengan karunia-Mu dari selain-Mu.',
        sumber: 'HR. Tirmidzi no. 3563' },
    { id: 'lunas-hutang', kategori: 'rezeki', judul: 'Doa Terbebas dari Hutang',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَقَهْرِ الرِّجَالِ',
        latin: 'Allahumma innii a\'uudzu bika minal hammi wal hazan, wal \'ajzi wal kasal, wal bukhli wal jubn, wa dhala\'id daini wa qahrir rijaal',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari kegelisahan, kesedihan, kelemahan, kemalasan, kekikiran, sifat pengecut, beban hutang, dan penindasan orang.',
        sumber: 'HR. Bukhari no. 2893' },
    { id: 'dari-hasad', kategori: 'perlindungan', judul: 'Doa Berlindung dari Hasad',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ الْحَاسِدِينَ وَمِنْ شَرِّ كُلِّ ذِي حَسَدٍ',
        latin: 'Allahumma innii a\'uudzu bika min syarril haasidiin wa min syarri kulli dzii hasad',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari keburukan orang yang hasad dan dari keburukan setiap yang memiliki kedengkian.',
        sumber: 'Doa salaf' },
    { id: 'dari-sihir', kategori: 'perlindungan', judul: 'Doa Berlindung dari Sihir',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ السِّحْرِ وَمِنْ شَرِّ كُلِّ سَاحِرٍ',
        latin: 'Allahumma innii a\'uudzu bika min syarris sihri wa min syarri kulli saahir',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari keburukan sihir dan dari keburukan setiap tukang sihir.',
        sumber: 'Doa salaf, dari Al-Mu\'awwidzatain' },
    // KATEGORI: UMUM
    { id: 'susah-hati', kategori: 'umum', judul: 'Doa Ketika Hati Susah',
        arab: 'لَا إِلَٰهَ إِلَّا اللَّهُ الْعَظِيمُ الْحَلِيمُ لَا إِلَٰهَ إِلَّا اللَّهُ رَبُّ الْعَرْشِ الْعَظِيمِ',
        latin: 'Laa ilaaha illallahul \'azhiimul haliim, laa ilaaha illallahu rabbul \'arsyil \'azhiim',
        arti: 'Tiada Tuhan selain Allah Yang Mahaagung, Maha Penyantun. Tiada Tuhan selain Allah, Tuhan pemilik Arsy yang agung.',
        sumber: 'HR. Bukhari no. 6345' },
    { id: 'sedih', kategori: 'umum', judul: 'Doa Ketika Sedih',
        arab: 'اللَّهُمَّ إِنِّي عَبْدُكَ ابْنُ عَبْدِكَ ابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ',
        latin: 'Allahumma innii \'abduka, ibnu \'abdika, ibnu amatika, naashiyatii bi yadik',
        arti: 'Ya Allah, aku adalah hamba-Mu, anak hamba-Mu, anak hamba perempuan-Mu. Ubun-ubunku di tangan-Mu.',
        sumber: 'HR. Ahmad no. 3712' },
    { id: 'kecemasan', kategori: 'umum', judul: 'Doa Ketika Cemas',
        arab: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ',
        latin: 'Allahumma innii a\'uudzu bika minal hammi wal hazan',
        arti: 'Ya Allah, aku berlindung kepada-Mu dari kegelisahan dan kesedihan.',
        sumber: 'HR. Bukhari no. 2893' },
    { id: 'kelapangan-hati', kategori: 'umum', judul: 'Doa Memohon Kelapangan Hati',
        arab: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي',
        latin: 'Rabbisyrah lii shadrii wa yassir lii amrii',
        arti: 'Tuhanku, lapangkanlah dadaku dan mudahkanlah urusanku.',
        sumber: 'QS. Thaha: 25-26' },
    { id: 'istiqamah', kategori: 'umum', judul: 'Doa Memohon Keteguhan Hati',
        arab: 'يَا مُقَلِّبَ الْقُلُوبِ ثَبِّتْ قَلْبِي عَلَى دِينِكَ',
        latin: 'Yaa muqallibal quluub, tsabbit qalbii \'alaa diinik',
        arti: 'Wahai Yang Membolak-balikkan hati, teguhkanlah hatiku pada agama-Mu.',
        sumber: 'HR. Tirmidzi no. 3522' },
];
