import type { CommandDefinition } from './contracts.js'

const COMMAND_COPY: Readonly<Record<string, string>> = {
  groupsetup: 'Mulai atau lanjutkan pengaturan dasar grup.',
  scene: 'Kelola adegan cerita roleplay di grup.',
  setscene: 'Nyalakan atau matikan fitur adegan cerita grup.',
  ic: 'Gunakan mode berbicara sebagai karakter dalam adegan.',
  ooc: 'Kembali berbicara sebagai dirimu sendiri di luar karakter.',
  pause: 'Jeda adegan yang sedang kamu kelola.',
  consent: 'Atur izin partisipasi dalam adegan.',
  safety: 'Lihat status sistem keamanan grup.',
  setsafety: 'Nyalakan atau matikan sistem pemeriksaan keamanan grup.',
  warn: 'Beri peringatan tercatat kepada anggota.',
  warnings: 'Lihat daftar peringatan aktif di grup.',
  clearwarn: 'Cabut peringatan berdasarkan ID.',
  report: 'Laporkan masalah ke pengurus grup.',
  cases: 'Lihat daftar laporan keamanan grup.',
  case: 'Lihat detail satu laporan keamanan.',
  claimcase: 'Ambil laporan untuk ditangani.',
  resolvecase: 'Tandai laporan keamanan selesai ditangani.',
  dismisscase: 'Tutup laporan yang tidak perlu ditindaklanjuti.',
  appeal: 'Ajukan keberatan atas laporan atau sanksi.',
  modaction: 'Jalankan tindakan moderasi pada anggota.',
  groupmode: 'Atur izin kirim pesan dan edit info grup.',
  modstatus: 'Lihat riwayat tindakan pengurus terakhir.',
  retcon: 'Tinjau usulan perubahan alur cerita roleplay.',
  handoff: 'Oper atau ambil alih giliran tugas pengurus.',
  continuity: 'Periksa keselarasan alur cerita dan catatan grup.',
  joinrequests: 'Lihat daftar permintaan masuk grup.',
  join: 'Terima atau tolak permintaan bergabung.',
  invite: 'Lihat atau buat tautan undangan grup.',
  knowledge: 'Lihat catatan penting grup yang tersimpan.',
  setknowledge: 'Nyalakan atau matikan penyimpanan catatan grup.',
  quote: 'Kutip pesan yang kamu balas.',
  bookmark: 'Simpan pesan pilihan ke dalam catatan grup.',
  bookmarks: 'Lihat daftar catatan yang tersimpan.',
  source: 'Lihat detail catatan berdasarkan ID.',
  forget: 'Hapus catatan yang pernah kamu simpan.',
  knowledgeexport: 'Ekspor arsip catatan grup.',
  find: 'Cari catatan yang tersimpan di grup.',
  ai: 'Tanya Allybot tanpa menyimpan riwayat percakapan.',
  translate: 'Terjemahkan teks ke bahasa pilihanmu.',
  summarize: 'Ringkas pesan atau teks panjang.',
  sticker: 'Ubah gambar menjadi sticker WhatsApp.',
  toimg: 'Ubah sticker menjadi gambar biasa.',
  togif: 'Ubah video pendek menjadi animasi GIF.',
  toaudio: 'Ekstrak audio dari video atau voice note.',
  suggest: 'Minta saran atau ide berdasarkan catatan.',
  ping: 'Cek kecepatan respons dan koneksi bot.',
  health: 'Cek status kesehatan sistem bot.',
  diag: 'Cek ringkas kondisi sistem bot.',
  diagnostics: 'Diagnostik lengkap kondisi sistem bot.',
  botprofile: 'Lihat profil dan info singkat bot.',
  owner: 'Lihat profil dan kontak Owner Allybot.',
  groupinfo: 'Lihat informasi grup dan status bot.',
  membercount: 'Lihat jumlah anggota dan admin grup.',
  admins: 'Lihat daftar admin grup.',
  members: 'Lihat daftar anggota grup.',
  memberinfo: 'Lihat peran dan profil seorang anggota.',
  link: 'Lihat tautan undangan masuk grup.',
  rules: 'Lihat peraturan grup yang berlaku.',
  ruleshistory: 'Lihat riwayat perubahan aturan grup.',
  setrules: 'Atur atau ubah peraturan grup.',
  clearrules: 'Hapus peraturan grup.',
  setwelcome: 'Atur pesan sambutan untuk anggota baru.',
  clearwelcome: 'Hapus pesan sambutan grup.',
  setleave: 'Atur pesan perpisahan saat anggota keluar.',
  clearleave: 'Hapus pesan perpisahan grup.',
  groupsettings: 'Lihat pengaturan grup yang aktif.',
  prefix: 'Lihat prefix command yang digunakan di grup.',
  setprefix: 'Ubah prefix command grup.',
  setlanguage: 'Atur bahasa balasan bot di grup.',
  settimezone: 'Atur zona waktu grup.',
  role: 'Lihat peranmu atau peran anggota lain.',
  permissions: 'Lihat daftar izin yang kamu miliki di grup.',
  afk: 'Atur status sedang tidak aktif (AFK).',
  commands: 'Lihat daftar command yang aktif.',
  cmds: 'Lihat daftar command yang aktif.',
  searchcmd: 'Cari command berdasarkan kata kunci.',
  about: 'Lihat penjelasan tentang Allybot.',
  version: 'Lihat informasi versi bot.',
  privacy: 'Lihat kebijakan privasi dan keamanan data.',
  support: 'Pusat bantuan dan penanganan kendala bot.',
  status: 'Lihat status operasional Allybot.',
  uptime: 'Lihat lama waktu bot aktif berjalan.',
  latency: 'Cek waktu respons dan latensi bot.',
  features: 'Lihat ringkasan fitur yang tersedia.',
  character: 'Lihat dan kelola profil karakter roleplay.',
  mood: 'Atur suasana hati atau ekspresi karakter.',
  emote: 'Kirim aksi narasi karakter roleplay.',
  calc: 'Hitung operasi matematika sederhana.',
  convert: 'Konversi satuan dasar.',
  time: 'Lihat waktu pada zona tertentu.',
  date: 'Lihat tanggal hari ini.',
  random: 'Acak angka dalam rentang tertentu.',
  choose: 'Pilih satu opsi secara acak.',
  flip: 'Lempar koin (head atau tail).',
  roll: 'Lempar dadu, misalnya 2d6.',
  dice: 'Lempar dadu, misalnya 2d6.',
  '8ball': 'Minta jawaban hiburan secara acak.',
  truth: 'Dapatkan pertanyaan truth seru.',
  dare: 'Dapatkan tantangan dare seru.',
  rps: 'Main batu-gunting-kertas melawan Allybot.',
}

export function commandDescription(command: CommandDefinition): string {
  return COMMAND_COPY[command.name.toLowerCase()] ?? command.description ?? 'Command tersedia.'
}
