import type { CommandDefinition } from './contracts.js'

const COMMAND_COPY: Readonly<Record<string, string>> = {
  chatlog: 'Atur apakah catatan chat grup ini dikirim ke Neon.',
  groupsetup: 'Mulai atau lanjutkan pengaturan dasar grup.',
  announce: 'Siapkan pengumuman untuk tujuan yang dipilih.',
  onboarding: 'Daftar atau periksa proses masuk dan pengaturan awal grup.',
  scene: 'Kelola adegan cerita bersama di grup.',
  setscene: 'Nyalakan atau matikan adegan cerita grup.',
  ic: 'Gunakan mode berbicara sebagai karakter di adegan.',
  ooc: 'Kembali berbicara sebagai dirimu sendiri di adegan.',
  pause: 'Jeda adegan yang sedang kamu kelola.',
  consent: 'Atur izinmu untuk ikut serta dalam adegan.',
  safety: 'Lihat mode keamanan grup.',
  setsafety: 'Nyalakan pemeriksaan keamanan atau matikan.',
  warn: 'Beri peringatan yang tercatat kepada anggota.',
  warnings: 'Lihat peringatan terbaru di grup.',
  clearwarn: 'Cabut peringatan berdasarkan ID.',
  report: 'Laporkan masalah kepada pengurus grup.',
  cases: 'Lihat laporan keamanan yang tersedia.',
  case: 'Lihat satu laporan keamanan.',
  claimcase: 'Ambil satu laporan untuk ditangani.',
  resolvecase: 'Tandai laporan sebagai selesai.',
  dismisscase: 'Tutup laporan yang tidak perlu ditindaklanjuti.',
  appeal: 'Ajukan keberatan atas laporan milikmu.',
  modaction: 'Kelola anggota dengan tindakan yang tersedia.',
  groupmode: 'Atur cara anggota mengirim pesan atau mengubah info grup.',
  modstatus: 'Lihat hasil tindakan pengurus terakhir.',
  retcon: 'Periksa usulan perubahan cerita atau catatan grup.',
  handoff: 'Serahkan atau ambil tugas pengurusan grup.',
  continuity: 'Periksa apakah catatan penting grup tetap selaras.',
  joinrequests: 'Lihat permintaan masuk ke grup.',
  join: 'Terima atau tolak permintaan masuk.',
  invite: 'Lihat atau kelola tautan undangan grup.',
  personalization: 'Lihat pengaturan pribadi dan grup yang berlaku.',
  setpersonalization: 'Nyalakan atau matikan pengaturan pribadi grup.',
  myprefs: 'Lihat pilihan balasan yang berlaku untukmu.',
  preferences: 'Atur cara bot merespons di grup.',
  mylanguage: 'Pilih bahasa balasan untukmu.',
  mytimezone: 'Atur zona waktu untuk pengingatmu.',
  quiet: 'Atur waktu tenang untukmu.',
  notify: 'Nyalakan atau matikan pemberitahuan untukmu.',
  verbosity: 'Atur panjang balasan bot.',
  format: 'Pilih bentuk balasan yang nyaman dibaca.',
  collab: 'Lihat fitur kerja sama grup yang sedang aktif.',
  setcollab: 'Nyalakan atau matikan fitur kerja sama grup.',
  setnativepoll: 'Pilih tampilan yang dipakai untuk voting.',
  poll: 'Buat atau kelola voting grup.',
  vote: 'Pilih jawaban pada voting.',
  remind: 'Buat pengingat untuk grup.',
  reminders: 'Lihat pengingat grup yang masih aktif.',
  remindcancel: 'Batalkan pengingat yang kamu buat.',
  task: 'Buat tugas untuk dikerjakan bersama.',
  tasks: 'Lihat daftar tugas grup.',
  taskdone: 'Tandai tugasmu sebagai selesai.',
  decision: 'Catat keputusan yang disepakati grup.',
  decisions: 'Lihat keputusan grup yang pernah dicatat.',
  agenda: 'Lihat agenda kegiatan grup.',
  knowledge: 'Lihat catatan yang sengaja disimpan.',
  setknowledge: 'Nyalakan atau matikan penyimpanan catatan pilihan pengguna.',
  quote: 'Lihat pesan yang kamu balas tanpa menyimpannya.',
  bookmark: 'Simpan pesan yang kamu pilih sebagai catatan.',
  bookmarks: 'Lihat daftar catatan yang disimpan.',
  source: 'Baca satu catatan berdasarkan ID.',
  forget: 'Hapus catatan milikmu.',
  knowledgeexport: 'Keluarkan catatan yang memang boleh dilihat.',
  canon: 'Kelola catatan cerita yang disepakati.',
  setcanon: 'Nyalakan atau matikan catatan cerita grup.',
  lore: 'Lihat informasi cerita yang sudah disetujui.',
  event: 'Buat dan kelola kegiatan grup.',
  calendar: 'Lihat jadwal kegiatan grup.',
  ai: 'Tanya Allybot tanpa menyimpan percakapan.',
  suggest: 'Minta saran dari catatan yang kamu pilih.',
  ping: 'Cek apakah bot sedang merespons.',
  health: 'Cek apakah bagian utama bot berjalan normal.',
  diag: 'Cek kondisi bot secara ringkas.',
  diagnostics: 'Cek kondisi bot secara ringkas.',
  botprofile: 'Lihat informasi singkat tentang bot.',
  owner: 'Lihat profil Owner Allybot.',
  groupinfo: 'Lihat informasi grup dan status bot.',
  membercount: 'Lihat jumlah anggota dan admin grup.',
  admins: 'Lihat daftar admin grup.',
  members: 'Lihat daftar anggota grup.',
  memberinfo: 'Lihat peran seorang anggota.',
  link: 'Lihat tautan masuk grup jika tersedia.',
  rules: 'Lihat aturan grup.',
  ruleshistory: 'Lihat perubahan aturan terbaru.',
  setrules: 'Atur aturan grup.',
  clearrules: 'Hapus aturan grup.',
  setwelcome: 'Atur pesan saat anggota baru masuk.',
  clearwelcome: 'Hapus pesan selamat datang khusus grup.',
  setleave: 'Atur pesan saat anggota keluar.',
  clearleave: 'Hapus pesan keluar khusus grup.',
  groupsettings: 'Lihat pengaturan grup yang sedang aktif.',
  prefix: 'Lihat tanda awal command yang dipakai grup.',
  setprefix: 'Ganti tanda awal command di grup.',
  setlanguage: 'Atur bahasa balasan bot di grup.',
  settimezone: 'Atur zona waktu grup.',
  role: 'Lihat peranmu atau peran anggota lain.',
  permissions: 'Lihat hal yang boleh kamu lakukan di grup.',
  afk: 'Beri tahu bahwa kamu sedang tidak aktif atau lihat statusmu.',
  commands: 'Lihat daftar command yang aktif.',
  cmds: 'Lihat daftar command yang aktif.',
  searchcmd: 'Cari command berdasarkan kata kunci.',
  about: 'Lihat penjelasan singkat tentang Allybot.',
  version: 'Lihat informasi versi yang aman.',
  privacy: 'Baca ringkasan cara Allybot menjaga data.',
  support: 'Lihat langkah bantuan saat command bermasalah.',
  status: 'Lihat status umum Allybot.',
  uptime: 'Lihat lama Allybot berjalan.',
  latency: 'Cek waktu respons Allybot.',
  features: 'Lihat ringkasan fitur yang tersedia.',
  character: 'Buat dan kelola tokoh untuk roleplay sosial.',
  mood: 'Atur suasana tokoh yang sedang dipakai.',
  calc: 'Hitung operasi matematika sederhana.',
  convert: 'Konversi satuan dasar.',
  time: 'Lihat waktu pada zona tertentu.',
  date: 'Lihat tanggal hari ini.',
  random: 'Pilih angka acak dalam rentang tertentu.',
  choose: 'Pilih satu opsi secara acak.',
  flip: 'Lempar koin.',
  roll: 'Lempar dadu, misalnya 2d6.',
  dice: 'Lempar dadu, misalnya 2d6.',
  '8ball': 'Minta jawaban hiburan secara acak.',
}

export function commandDescription(command: CommandDefinition): string {
  return COMMAND_COPY[command.name.toLowerCase()] ?? command.description ?? 'Command tersedia.'
}
