import type { CommandDefinition } from './contracts.js'

const COMMAND_COPY: Readonly<Record<string, string>> = {
  // --- GROUP ---
  groupinfo: 'Cek detail nama, setelan, dan status bot di grup.',
  membercount: 'Hitung total anggota dan jumlah admin grup.',
  admins: 'Lihat daftar admin yang sedang bertugas di grup.',
  members: 'Lihat seluruh daftar anggota yang ada di grup.',
  memberinfo: 'Lihat profil singkat dan peran anggota di grup.',
  rules: 'Baca peraturan yang berlaku di grup ini.',
  ruleshistory: 'Lihat riwayat pembaruan peraturan grup.',
  setrules: 'Atur atau ubah peraturan untuk grup ini.',
  clearrules: 'Hapus peraturan grup yang tersimpan.',
  welcome: 'Nyalakan atau matikan ucapan selamat datang member baru.',
  setwelcome: 'Buat pesan sambutan kustom untuk member baru.',
  clearwelcome: 'Hapus pesan sambutan kustom member baru.',
  left: 'Nyalakan atau matikan ucapan perpisahan saat member keluar.',
  setleave: 'Buat pesan perpisahan kustom saat member keluar grup.',
  clearleave: 'Hapus pesan perpisahan grup.',
  afk: 'Pasang status istirahat agar bot memberi tahu jika ada yang tag kamu.',
  tagme: 'Minta bot me-mention akunmu sendiri di chat grup.',
  prefix: 'Cek simbol pemanggil bot yang aktif di grup.',
  setprefix: 'Ganti simbol pemanggil bot di grup ini.',
  link: 'Tampilkan tautan undangan masuk grup.',
  invite: 'Tampilkan tautan undangan masuk grup.',
  role: 'Lihat peran kamu atau member lain di grup.',
  permissions: 'Cek daftar izin yang kamu miliki di grup.',
  groupsettings: 'Lihat setelan grup yang sedang aktif.',
  setlanguage: 'Atur bahasa balasan bot di grup.',
  settimezone: 'Atur zona waktu grup.',
  suggest: 'Kirim kritik atau saran secara anonim ke pengurus bot.',

  // --- ADMIN TOOLS ---
  kick: 'Keluarkan member dari grup.',
  ban: 'Keluarkan dan cegah member masuk kembali ke grup.',
  unban: 'Hapus member dari daftar blokir grup.',
  mute: 'Heningkan member sementara (pesannya otomatis dihapus).',
  unmute: 'Buka kembali izin berbicara member yang di-mute.',
  warn: 'Beri peringatan pelanggaran kepada member.',
  warnings: 'Lihat daftar peringatan aktif yang dimiliki member.',
  unwarn: 'Kurangi hitungan peringatan member.',
  clearwarn: 'Hapus seluruh kartu peringatan member sekaligus.',
  setlimit: 'Atur batas maksimal peringatan sebelum member otomatis di-kick.',
  antilink: 'Nyalakan atau matikan filter penghapus link otomatis.',
  antispam: 'Nyalakan atau matikan proteksi chat cepat/spam.',
  antitoxic: 'Nyalakan atau matikan sensor kata kasar di grup.',
  safety: 'Cek status sistem pengawasan keamanan grup.',
  setsafety: 'Atur mode pengawasan keamanan grup.',
  auditverify: 'Cek keaslian catatan riwayat tindakan admin.',
  lock: 'Kunci grup agar hanya admin yang dapat mengirim pesan.',
  unlock: 'Buka kunci grup agar semua member dapat mengobrol.',
  groupmode: 'Atur mode ruang obrolan grup.',
  promote: 'Angkat member menjadi admin grup.',
  demote: 'Turunkan admin menjadi member biasa.',
  tagall: 'Panggil seluruh anggota grup dalam satu pesan.',
  hidetag: 'Kirim pengumuman penting ke seluruh member tanpa deretan tag.',
  del: 'Hapus pesan di grup yang keliru atau melanggar aturan.',
  clear: 'Bersihkan pesan terbaru di obrolan grup.',
  leave: 'Petunjuk perintah keluar grup.',
  botleave: 'Perintahkan bot untuk keluar dari grup ini (Khusus Owner).',
  modaction: 'Jalankan tindakan pengamanan grup.',
  modstatus: 'Lihat riwayat tindakan admin terakhir.',
  report: 'Laporkan masalah atau pelanggaran ke pengurus secara aman.',
  cases: 'Lihat daftar laporan member di grup.',
  case: 'Lihat rincian laporan tertentu berdasarkan ID.',
  setkotaksaran: 'Atur grup ini sebagai kotak penampung saran (Owner).',
  setreportbox: 'Atur grup ini sebagai kotak penampung laporan (Owner).',
  replysaran: 'Balas saran masuk berdasarkan nomor tiket pengirim.',
  replyreport: 'Balas laporan masuk berdasarkan nomor tiket pelapor.',
  blocksaran: 'Blokir tiket saran pengirim yang menyalahgunakan kotak saran.',
  blockreport: 'Blokir tiket pengirim yang menyalahgunakan kotak laporan.',

  // --- YOUR CHARACTER ---
  character: 'Buka jendela kartu profil karakter roleplay-mu.',
  stats: 'Cek rincian atribut kekuatan dan statistik karakter.',
  inspectchar: 'Lihat kartu status karakter milik pemain lain.',
  daftar: 'Registrasi awal pembuatan lembar karakter baru.',
  alokasi: 'Bagikan poin bebas ke atribut kekuatan karakter.',
  pensiun: 'Pensiunkan karakter secara sukarela.',
  savecharacter: 'Simpan data lembar karakter yang baru dibuat.',
  timerp: 'Lihat penyesuaian waktu in-game dalam roleplay.',
  setlevel: 'Atur level karakter (Khusus Pengurus).',
  setrank: 'Atur rank karakter (Khusus Pengurus).',
  resetstats: 'Kembalikan seluruh poin atribut karakter (Khusus Pengurus).',
  forceretire: 'Pensiunkan paksa karakter pemain (Khusus Pengurus).',
  givetoken: 'Beri bonus token karakter (Khusus Pengurus).',
  bank: 'Buka buku tabungan mata uang Vela.',
  wallet: 'Cek saldo koin Vela di dompetmu.',
  vela: 'Cek saldo koin Vela di dompetmu.',
  pay: 'Kirim atau transfer koin Vela ke pemain lain.',
  bankreward: 'Beri hadiah koin Vela kepada member (Khusus Pengurus).',
  bankpolicy: 'Cek aturan perbankan dan ekonomi grup.',
  tax: 'Cek informasi tarif pajak transaksi koin Vela.',
  taxbayar: 'Bayar tagihan pajak koin Vela.',

  // --- TOOLS ---
  ai: 'Tanya asisten cerdas (bisa jawab teks, analisis gambar, dan dokumen).',
  ally: 'Tanya asisten cerdas (bisa jawab teks, analisis gambar, dan dokumen).',
  translate: 'Terjemahkan kalimat ke berbagai bahasa.',
  summarize: 'Buat rangkuman padat dari teks atau artikel panjang.',
  tts: 'Ubah tulisan menjadi suara rekaman voice note.',
  text2img: 'Buat ilustrasi gambar dari deskripsi teks.',
  img2text: 'Ekstrak dan baca teks tulisan dari gambar.',
  sticker: 'Ubah foto atau video pendek menjadi stiker WhatsApp.',
  s: 'Ubah foto atau video pendek menjadi stiker WhatsApp.',
  stickerwm: 'Buat stiker dengan nama pack dan author kustom.',
  swm: 'Buat stiker dengan nama pack dan author kustom.',
  brat: 'Buat stiker teks aesthetic buram khas album brat.',
  bratvid: 'Buat stiker animasi bergerak teks khas album brat.',
  smeme: 'Buat stiker meme dengan teks atas dan bawah.',
  emojimix: 'Gabungkan dua emoji berbeda jadi satu stiker lucu.',
  qc: 'Ubah pesan chat menjadi stiker kutipan dengan foto profil.',
  iqc: 'Buat fake chat aesthetic bergaya WhatsApp iOS context menu (gambar).',
  iqcs: 'Buat stiker fake chat aesthetic bergaya WhatsApp iOS context menu.',
  x: 'Buat kartu postingan Twitter/X mockup yang elegan.',
  tweet: 'Buat kartu postingan Twitter/X mockup yang elegan.',
  ttstalk: 'Lihat profil dan statistik akun TikTok secara visual.',
  igstalk: 'Lihat profil dan statistik akun Instagram secara visual.',
  toimg: 'Ubah stiker menjadi gambar foto biasa.',
  togif: 'Ubah stiker bergerak menjadi animasi GIF.',
  toaudio: 'Ambil file suara dari video atau voice note.',
  tovideo: 'Konversi animasi stiker menjadi video.',
  compress: 'Kompresi dan perkecil ukuran file media.',
  hd: 'Pertajam resolusi gambar dan foto yang buram.',
  spack: 'Kirim seluruh stiker dari tautan paket WhatsApp.',
  removebg: 'Hapus latar belakang foto secara otomatis.',
  google: 'Cari informasi kilat dari mesin pencari Google.',
  image: 'Cari foto atau gambar dari internet.',
  wiki: 'Baca ringkasan artikel ensiklopedia Wikipedia.',
  cuaca: 'Pantau perkiraan cuaca dan suhu di kotamu.',
  lirik: 'Cari lirik lagu favoritmu.',
  pin: 'Cari gambar inspirasi dari Pinterest.',
  pixiv: 'Cari karya ilustrasi dari Pixiv.',
  tik: 'Unduh video TikTok tanpa watermark.',
  tik2mp3: 'Unduh audio musik dari video TikTok.',
  dl: 'Unduh video dari tautan media sosial.',
  multidl: 'Unduh media dari berbagai tautan sosmed.',
  ping: 'Cek kecepatan respon dan latensi bot.',
  botprofile: 'Buka profil lengkap dan pengenalan resmi tentang Allybot.',
  health: 'Cek status kelancaran sistem bot.',
  diag: 'Pemeriksaan ringkas performa sistem bot.',
  diagnostics: 'Diagnostik lengkap kesehatan sistem bot.',
  about: 'Lihat info pengembang dan fitur Allybot.',
  version: 'Cek nomor versi Allybot saat ini.',
  support: 'Pusat bantuan jika mengalami kendala bot.',
  commands: 'Lihat daftar command yang dapat digunakan.',
  cmds: 'Lihat daftar command yang dapat digunakan.',
  searchcmd: 'Cari command yang kamu butuhkan dengan kata kunci.',
  calc: 'Hitung operasi matematika sederhana.',
  convert: 'Konversi satuan ukuran dasar.',
  time: 'Lihat jam saat ini di zona waktu tertentu.',
  date: 'Lihat tanggal hari ini.',

  // --- FUN ---
  rps: 'Tantang temanmu duel batu-gunting-kertas lewat chat pribadi.',
  suit: 'Tantang temanmu duel batu-gunting-kertas lewat chat pribadi.',
  random: 'Acak angka keberuntungan dalam rentang tertentu.',
  choose: 'Minta bot bantu menentukan satu dari beberapa pilihan.',
  flip: 'Lempar koin penentu pilihan (Kepala atau Ekor).',
  roll: 'Lempar dadu keberuntungan (misalnya: 1d6, 2d20).',
  dice: 'Lempar dadu keberuntungan (misalnya: 1d6, 2d20).',
  '8ball': 'Tanya bola ajaib untuk jawaban hiburan seru.',
  truth: 'Dapatkan pertanyaan kejujuran seru untuk menguji teman.',
  dare: 'Dapatkan tantangan aksi seru untuk dimainkan di grup.',
}

export function commandDescription(command: CommandDefinition): string {
  return COMMAND_COPY[command.name.toLowerCase()] ?? command.description ?? 'Command tersedia.'
}
